---

- name: "check if /usr/local/bin/nats exists"
  stat:
    path: "/usr/local/bin/nats"
  register: nats_cli

- name: install nats cli
  block:
    - name: unarchive nats cli
      unarchive:
        src: "https://github.com/nats-io/natscli/releases/download/{{ nats_cli_version }}/nats-{{ nats_cli_version }}-linux-amd64.zip"
        dest: /tmp
        copy: no

    - name: move nats cli file
      copy: 
        src: "/tmp/nats-{{ nats_cli_version }}-linux-amd64/nats" 
        dest: "/usr/local/bin/nats" 
        remote_src: yes 
      
    - name: make nats executable
      file: 
        path: "/usr/local/bin/nats"
        mode: 0755
  when: nats_cli.stat.exists == false
