---

- name: "Check if /usr/local/bin/nats exists"
  ansible.builtin.stat:
    path: "/usr/local/bin/nats"
  register: nats_cli

- name: Install nats cli
  when: not nats_cli.stat.exists
  block:
    - name: Unarchive nats cli
      ansible.builtin.unarchive:
        src: "https://github.com/nats-io/natscli/releases/download/{{ nats_cli_version }}/nats-{{ nats_cli_version }}-linux-amd64.zip"
        dest: /tmp
        copy: no

    - name: Move nats cli file
      ansible.builtin.copy: 
        src: "/tmp/nats-{{ nats_cli_version }}-linux-amd64/nats" 
        dest: "/usr/local/bin/nats" 
        mode: 0755
        remote_src: yes 
      
    
