---
- name: Install logrotate
  ansible.builtin.apt:
    name: logrotate

- name: Configure logrotate for nats-server
  ansible.builtin.template: 
    src: logrotate.j2 
    dest: "/etc/logrotate.d/nats-server" 
    mode: 0644