---
# handlers file for nats

- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true
  when:
    - not skip_systemd

- name: Restart nats-server
  ansible.builtin.service: 
    name: nats-server 
    state: restarted
    enabled: yes
  when:
    - not skip_systemd