---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: default-${MOLECULE_DISTRO:-debian11}
    image: geerlingguy/docker-${MOLECULE_DISTRO:-debian11}-ansible:latest
    pre_build_image: true
provisioner:
  name: ansible
  playbooks:
    prepare: ../shared/playbooks/prepare.yml
    converge: ${MOLECULE_PLAYBOOK:-converge.yml}
verifier:
  name: ansible
